development:
  adapter: postgresql
  encoding: unicode
  database: jobsite
  host: localhost
  pool: 5
  username: 'postgres'
  password: 'password12'
  
production:
  adapter: postgresql
  statement_limit: 200
  username: ENV['Username']
  password: ENV['Password']
